import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from './components/wrapper/SessionWrapper';
import ClientLayout from './components/wrapper/NavBarWrapper';
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
// import NavBarWrapper from "./components/wrapper/NavBarWrapper";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "logo.png",
  },
};

const NavbarWrapper = dynamic(
  ()=>{
    return import("./components/wrapper/NavBarWrapper");
  },
  {ssr: false}
)

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <SessionWrapper>
      <html lang="en" data-theme="dark">
        <body className={inter.className}>
          <NavbarWrapper session={session}>
            {children}
          </NavbarWrapper>
        </body>
      </html>
    </SessionWrapper>
  );
}